/**
 * Sample data, shaped exactly like what the real backend is expected to
 * return. Swap this out for nothing — once VITE_API_BASE_URL is set,
 * pilgrimService.js talks to the real endpoint automatically.
 */
export const MOCK_PILGRIMS = [
  {
    campId: 'CMP-1001',
    fullName: 'Aisha Bello',
    category: 'Elder, VIP',
    gender: 'Female',
    pilgrimGroup: 'Group A',
    schoolName: 'Al-Furqan Academy',
    phone: '+234 803 111 2233',
    additionalInfo: 'Requires wheelchair assistance at boarding',
  },
  {
    campId: 'CMP-1002',
    fullName: 'Ibrahim Musa',
    category: 'Student',
    gender: 'Male',
    pilgrimGroup: 'Group B',
    schoolName: 'Nur-ul-Islam College',
    phone: '+234 805 222 3344',
    additionalInfo: '',
  },
  {
    campId: 'CMP-1003',
    fullName: 'Fatima Yusuf',
    category: 'Volunteer, Medical',
    gender: 'Female',
    pilgrimGroup: 'Group A',
    schoolName: 'Zainab Girls College',
    phone: '+234 806 333 4455',
    additionalInfo: 'Registered nurse, on-call for camp clinic',
  },
  {
    campId: 'CMP-1004',
    fullName: 'Umar Suleiman',
    category: 'Student',
    gender: 'Male',
    pilgrimGroup: 'Group C',
    schoolName: 'Al-Furqan Academy',
    phone: '+234 807 444 5566',
    additionalInfo: 'Shares room with CMP-1006',
  },
  {
    campId: 'CMP-1005',
    fullName: 'Khadija Aliyu',
    category: 'Elder',
    gender: 'Female',
    pilgrimGroup: 'Group D',
    schoolName: 'Daarul Uloom Institute',
    phone: '+234 808 555 6677',
    additionalInfo: 'Diabetic — needs meal schedule reminders',
  },
  {
    campId: 'CMP-1006',
    fullName: 'Yusuf Abdullahi',
    category: 'Student, Sports',
    gender: 'Male',
    pilgrimGroup: 'Group C',
    schoolName: 'Nur-ul-Islam College',
    phone: '+234 809 666 7788',
    additionalInfo: '',
  },
  {
    campId: 'CMP-1007',
    fullName: 'Maryam Sani',
    category: 'Staff',
    gender: 'Female',
    pilgrimGroup: 'Group A',
    schoolName: 'Zainab Girls College',
    phone: '+234 810 777 8899',
    additionalInfo: 'Group coordinator for Group A',
  },
  {
    campId: 'CMP-1008',
    fullName: 'Hassan Garba',
    category: 'VIP',
    gender: 'Male',
    pilgrimGroup: 'Group B',
    schoolName: 'Daarul Uloom Institute',
    phone: '+234 811 888 9900',
    additionalInfo: 'Travelling with family (2 dependents)',
  },
  {
    campId: 'CMP-1009',
    fullName: 'Zainab Lawal',
    category: 'Student, Media',
    gender: 'Female',
    pilgrimGroup: 'Group D',
    schoolName: 'Al-Furqan Academy',
    phone: '+234 812 999 0011',
    additionalInfo: 'Documenting the trip for the school bulletin',
  },
];
